services:
  - type: web
    name: webhook-service-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: PORT
        value: 10000
      - key: VITE_API_URL
        value: https://webhook-service-api.onrender.com/api
    healthCheckPath: /
    autoDeploy: true

  - type: web
    name: webhook-service-api
    env: python
    rootDir: api
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: POSTGRES_DB
        value: webhook_db_unb3
      - key: POSTGRES_USER
        value: webhook_db_unb3_user
      - key: POSTGRES_PASSWORD
        value: VQn3gIJLJxxaEXIzFEA1cJCEP2BH1knW
      - key: DATABASE_URL
        value: postgresql://webhook_db_unb3_user:VQn3gIJLJxxaEXIzFEA1cJCEP2BH1knW@dpg-d0b8oap5pdvs73cfcpag-a/webhook_db_unb3
      - key: REDIS_URL
        value: redis://red-d0b8s9pr0fns73d8efp0:6379
      - key: CELERY_BROKER_URL
        value: redis://red-d0b8s9pr0fns73d8efp0:6379/1
      - key: CELERY_RESULT_BACKEND
        value: redis://red-d0b8s9pr0fns73d8efp0:6379/2
    healthCheckPath: /docs
    autoDeploy: true
