services:
  - type: web
    name: webhook-service-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: PORT
        value: 10000
      - key: VITE_API_URL
        value: https://webhook-backend-88w7.onrender.com/api
    healthCheckPath: /
    autoDeploy: true

  - type: web
    name: webhook-service-api
    env: python
    rootDir: api
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PORT
        value: 8000
      - key: POSTGRES_DB
        fromDatabase:
          name: webhook-db
          property: database
      - key: POSTGRES_USER
        fromDatabase:
          name: webhook-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: webhook-db
          property: password
      - key: DATABASE_URL
        fromDatabase:
          name: webhook-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: webhook-redis
          type: redis
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          name: webhook-redis
          type: redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          name: webhook-redis
          type: redis
          property: connectionString
      - key: MAX_RETRY_ATTEMPTS
        value: "5"
      - key: INITIAL_RETRY_DELAY
        value: "10"
      - key: MAX_RETRY_DELAY
        value: "900"
      - key: DELIVERY_TIMEOUT
        value: "10"
      - key: LOG_RETENTION_DAYS
        value: "3"
    healthCheckPath: /docs
    autoDeploy: true

  - type: redis
    name: webhook-redis
    ipAllowList: []
    plan: free

  - type: postgres
    name: webhook-db
    ipAllowList: []
    plan: free
